### ISSUE TITLE
Default settings are missing

### ISSUE THREAD

**Issue by sberan** [webBoxio/atom-term2#110]
[Enter steps to reproduce below:]

1. open any file
2. hit cmd + alt + up arrow
3. kaboom!

**Atom Version**: 0.192.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.2
**Thrown From**: [term2](https://github.com/webBoxio/atom-term2) package, v0.9.5

### Stack Trace

Uncaught TypeError: Cannot read property 'value' of undefined

```
At /Users/sberan/.atom/packages/term2/index.coffee:61

TypeError: Cannot read property 'value' of undefined
  at Object.module.exports.getColors (/Users/sberan/.atom/packages/term2/index.coffee:61:49)
  at Object.module.exports.createTermView (/Users/sberan/.atom/packages/term2/index.coffee:76:26)
  at Object.module.exports.splitTerm (/Users/sberan/.atom/packages/term2/index.coffee:86:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:238:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```

### Commands

```
     -0:38.6 term2:open-split-up (a.btn-issue.btn.btn-error)
     -0:33.2 core:close (div.settings-view.pane-item)
     -0:31.8 term2:open-split-up (atom-text-editor.editor.is-focused)
     -0:23.0 core:close (atom-text-editor.editor.is-focused)
  2x -0:08.2 term2:open-split-up (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "useReactEditor": true,
    "disabledPackages": [
      "term",
      "whitespace"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-typescript, v2.15.7
auto-detect-indentation, v0.4.0
autocomplete-plus, v2.7.1
language-ejs, v0.1.0
language-gradle, v0.0.3
language-typescript, v0.15.0
last-cursor-position, v0.8.0
layout-manager, v0.2.3
linter, v0.12.0
minimap, v4.7.6
string-cols, v0.0.0
term2, v0.9.5
web-browser, v1.4.4

# Dev
No dev packages
```

**Comment by OGrape** [comment]
Insert 
~~~
  core:
    {}
  term2:
    colors:
      normalBlack: "#2e3436"
      normalRed: "#cc0000"
      normalGreen: "#4e9a06"
      normalYellow: "#c4a000"
      normalBlue: "#3465a4"
      normalPurple: "#75507b"
      normalCyan: "#06989a"
      normalWhite: "#d3d7cf"
      brightBlack: "#555753"
      brightRed: "#ef2929"
      brightGreen: "#8ae234"
      brightYellow: "#fce94f"
      brightBlue: "#729fcf"
      brightPurple: "#ad7fa8"
      brightCyan: "#34e2e2"
      brightWhite: "#eeeeec"
      background: "#272B33"
      foreground: "#f0f0f0"
~~~
to `config.cson` (Under Open Your Config) solves the problem

**Comment by MoOx** [comment]
Not sure if it's still relevant.
