### ISSUE TITLE
Term2 doesn't open up!

### ISSUE THREAD

**Issue by imalitavakoli** [webBoxio/atom-term2#122]
When I press `Ctrl+Alt+T` to open up the terminal Atom says:
> Failed to activate the atom-term2 package
> Cannot find module 'fs-plus'

And here is the stack trace:

**Atom Version**: 0.199.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [atom-term2](https://github.com/webBoxio/atom-term2) package, v0.9.5

### Stack Trace

Failed to activate the atom-term2 package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\Ali\AppData\Local\atom\app-0.199.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/C:/Users/Ali/.atom/packages/atom-term2/lib/TermView.coffee:12:8)
    at Object.<anonymous> (/C:/Users/Ali/.atom/packages/atom-term2/lib/TermView.coffee:273:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\Ali\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

### Commands

```
     -0:02.6.0 term2:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "atom-terminal"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-term2, v0.9.5
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by lnishan** [comment]
Same with Win 7 Pro (64bit)
```
apm  0.167.0
npm  2.5.1
node 0.10.35
python 2.7.9
git 1.9.4.msysgit.2
visual studio 2013
```

I managed to get a little bit further with
```
npm install fs-plus
npm install debounce
npm install atom-term.js
npm install keypather
npm install atom-space-pen-views
```
but here's this error. Unfortunately I don't know Coffeescript / JQuery / Javascript / Node to continue debug.
```
TypeError: Cannot read property 'toLowerCase' of undefined
    at /C:/Users/user/.atom/packages/atom-term2/index.coffee:43:36
    at Object.<anonymous> (/C:/Users/user/.atom/packages/atom-term2/index.coffee:51:9)
    at Object.<anonymous> (/C:/Users/user/.atom/packages/atom-term2/index.coffee:169:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\user\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Package.module.exports.Package.requireMainModule (C:\Users\user\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package.js:707:34)
```
Same with Win 7 Pro (64bit)
```
apm  0.167.0
npm  2.5.1
node 0.10.35
python 2.7.9
git 1.9.4.msysgit.2
visual studio 2013
```

I managed to get a little bit further with
```
npm install fs-plus
npm install debounce
npm install atom-term.js
npm install keypather
npm install atom-space-pen-views
```

```
TypeError: Cannot read property 'toLowerCase' of undefined
    at /C:/Users/user/.atom/packages/atom-term2/index.coffee:43:36
    at Object.<anonymous> (/C:/Users/user/.atom/packages/atom-term2/index.coffee:51:9)
    at Object.<anonymous> (/C:/Users/user/.atom/packages/atom-term2/index.coffee:169:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\user\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Package.module.exports.Package.requireMainModule (C:\Users\user\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package.js:707:34)
```

**Comment by lnishan** [comment]
I would assume it's most likely the issue with pty.js again,  
as the errors I'm getting from other approaches point that way.

**Comment by lnishan** [comment]
Alright, after digging a little bit further,  
I believe this is an issue with pty.js on Windows.  
Getting some error messages with this file while trying to install pty.js manually.
```
..\src\win\pty.cc
```
I'm going to try and resolve this issue later.

**Comment by lnishan** [comment]
I have patched pty.js a little bit and was able to manually install pty.js and term2.  
However
```
TypeError: Cannot read property 'toLowerCase' of undefined
    at /C:/Users/user/.atom/packages/atom-term2/index.coffee:43:36
```
After removing toLowerCase() at that particular line
```
TypeError: Cannot read property 'value' of undefined
    at Object.module.exports.getColors (/C:/Users/user/.atom/packages/atom-term2/index.coffee:67:53)
```
Unfortunately I don't know coffee script and how atom plugins work,
so I guess I'll have to stop here.

**Comment by lnishan** [comment]
It appears that even with my patched version of pty.js. (also fixed a minor bug in winpty)  
The package cannot be activated. The error messages are the same as mentioned above.  
The installation process went through though.

**Comment by charlieroberts** [comment]
`TypeError: Cannot read property 'value' of undefined
    at Object.module.exports.getColors (/C:/Users/user/.atom/packages/atom-term2/index.coffee:67:53)`

I have the same problem, although for me the error occurs on line 108 with the getColors method. OS X 10.10.3, Atom 0.201

**Comment by MoOx** [comment]
Did you all have "At Cannot find module 'fs-plus'" ?

If yes, maybe the installation of this dep is causing some issue :/

**Comment by MoOx** [comment]
I guess it was a temporary issue.
