### ISSUE TITLE
Uncaught TypeError: Cannot set property '0' of undefined

### ISSUE THREAD

**Issue by dadaphl** [webBoxio/atom-term2#137]
[Enter steps to reproduce below:]

1. Attach to Tmux Session. (Session has 3 panes, one pane is Mosh-SSH'ed to machine with Tmux, one pane has cmus running, last pane normal zsh shell)
2. resize Atom window

**Atom Version**: 1.0.0
**System**: Mac OS X 10.9.5
**Thrown From**: [term2](https://github.com/webBoxio/atom-term2) package, v0.9.9

### Stack Trace

Uncaught TypeError: Cannot set property '0' of undefined

```
At /Users/philipp/.atom/packages/term2/node_modules/atom-term.js/src/term.js:1504

TypeError: Cannot set property '0' of undefined
  at Terminal.write (/Users/philipp/.atom/packages/term2/node_modules/atom-term.js/src/term.js:1504:55)
  at /Users/philipp/.atom/packages/term2/lib/TermView.coffee:48:50
  at Task.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:118:15)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:81:31)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at handleMessage (child_process.js:306:10)
  at Pipe.channel.onread (child_process.js:334:11)

```

### Commands

```
  5x -3:08.8.0 blur (div.terminal)
  5x -2:55.3.0 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -2:50.9.0 core:close (atom-text-editor.editor.vim-mode.command-mode.is-focused)
 14x -2:50.9.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  3x -2:38.2.0 core:cancel (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-zenburn.theme-atom-dark-ui)
  4x -2:26.8.0 blur (div.terminal)
     -2:16.5.0 core:move-down (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-zenburn.theme-atom-dark-ui)
     -2:16.1.0 core:move-up (div.terminal)
     -2:15.7.0 core:confirm (div.terminal)
  3x -2:12.8.0 blur (div.terminal)
     -2:00.8.0 core:move-up (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-zenburn.theme-atom-dark-ui)
     -2:00.3.0 core:confirm (div.terminal)
 17x -2:00.3.0 blur (div.terminal)
     -1:33.2.0 core:move-up (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-zenburn.theme-atom-dark-ui)
     -1:32.6.0 core:confirm (div.terminal)
 27x -1:32.5.0 blur (div.terminal)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "zenburn"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "metrics"
    ]
  },
  "term2": {}
}
```

### Installed Packages

```coffee
# User
term2, v0.9.9
vim-mode, v0.54.0
vim-mode-visual-block, v0.2.4
vim-surround, v0.7.2
zenburn, v3.0.0

# Dev
No dev packages
```

**Comment by MoOx** [comment]
dup of #138
