### ISSUE TITLE
Cannot install on *inx

### ISSUE THREAD

**Issue by soumyaray** [webBoxio/atom-term2#44]
Have tried through GUI package manager and apm.  Uninstalled old 0.9.2 first.

produces error:
```
> pty.js@0.2.4 install /private/var/folders/fy/2pgth7nd7h7d345vrgp3l7j00000gn/T/apm-install-dir-114723-6886-qv6r6q/node_modules/term2/node_modules/pty.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o

npm http GET https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/atom-term.js/0.0.55
npm http GET https://registry.npmjs.org/debounce/0.0.3
npm http GET https://registry.npmjs.org/keypather
npm http GET https://github.com/chjj/pty.js/archive/master.tar.gz
npm http 304 https://registry.npmjs.org/keypather
npm http 304 https://registry.npmjs.org/debounce/0.0.3
npm http 304 https://registry.npmjs.org/fs-plus
npm http 304 https://registry.npmjs.org/atom-term.js/0.0.55
npm http 200 https://github.com/chjj/pty.js/archive/master.tar.gz
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/extend
npm http 200 https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/nan/-/nan-1.0.0.tgz
npm http GET https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/underscore
npm http 200 https://registry.npmjs.org/nan/-/nan-1.0.0.tgz
../src/unix/pty.cc:37:10: fatal error: '/usr/include/util.h' file not found
#include </usr/include/util.h>
         ^
1 error generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 13.3.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/fy/2pgth7nd7h7d345vrgp3l7j00000gn/T/apm-install-dir-114723-6886-qv6r6q/node_modules/term2/node_modules/pty.js
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! pty.js@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.4 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.3.0
npm ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/Users/soumyaray/.atom/.apmrc" "install" "/var/folders/fy/2pgth7nd7h7d345vrgp3l7j00000gn/T/d-114723-6886-8pv0g5/package.tgz" "--target=0.11.13" "--arch=x64"
npm ERR! cwd /private/var/folders/fy/2pgth7nd7h7d345vrgp3l7j00000gn/T/apm-install-dir-114723-6886-qv6r6q
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /private/var/folders/fy/2pgth7nd7h7d345vrgp3l7j00000gn/T/apm-install-dir-114723-6886-qv6r6q/npm-debug.log
npm ERR! not ok code 0

**Comment by redvex** [comment]
@kbowerma I have xcode installed… I've tried to install manually  node-gyp and remove  node-gyp folder from .atom folder… but still same error

**Comment by kbowerma** [comment]
Sorry @redvex it quit working for me too.   I don't know if it was an apple update, atom update or aterm2 update that killed it.

**Comment by MoOx** [comment]
Is there still people having trouble on osx/linux ?

**Comment by redvex** [comment]
No, it’s ok now :)

thanks!
