### ISSUE TITLE
Term2 not opening since recent upgrade to Atom

### ISSUE THREAD

**Issue by thejayvm** [webBoxio/atom-term2#61]
OS: Mac OS X 10.9/10.10
Atom Version: 0.138.0

When ever I open a term2 tab now, all I get is a blank screen with a blinking cursor. I get the following error dump in the inspector window.

```
/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45
      Module._extensions[extension](this, filename);
                                   ^
Module version mismatch. Expected 16, got 14. /Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45
      Module._extensions[extension](this, filename);
                                   ^
Error: Module version mismatch. Expected 16, got 14.
  at Error (native)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/Users/jason/.atom/packages/term2/node_modules/pty.js/lib/pty.js:10:11)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/Users/jason/.atom/packages/term2/node_modules/pty.js/index.js:2:18)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/Users/jason/.atom/packages/term2/lib/pty.coffee:3:7)
  at Object.<anonymous> (/Users/jason/.atom/packages/term2/lib/pty.coffee:3:1)
  at Module._compile (module.js:468:26)
  at Object.requireCoffeeScript [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/coffee-cache.js:61:19)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/task-bootstrap.js:95:13)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/task-bootstrap.js:97:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at [eval]:3:1
  at Object.exports.runInThisContext (vm.js:74:17)
  at Object.<anonymous> ([eval]-wrapper:6:22)
  at Module._compile (module.js:468:26)
  at evalScript (node.js:465:25)
  at startup (node.js:91:7)
  at node.js:848:3
```
```
 /Applications/Atom.app/Contents/Resources/app/src/task.js:51
Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/task-bootstrap.js:82:23)
  at process.emit (events.js:110:17)
  at handleMessage (child_process.js:323:10)
  at Pipe.channel.onread (child_process.js:351:11)
```

**Comment by MoOx** [comment]
Seems outdate feel free to repopen if relevant.
