### ISSUE TITLE
0.9.4 install fails

### ISSUE THREAD

**Issue by thetutlage** [webBoxio/atom-term2#63]
It still fails i have pasted error trace

```
> pty.js@0.2.4 install /private/var/folders/mb/281v60z50ml4tw4qk9x25hr40000gn/T/apm-install-dir-114101-42744-13l3a82/node_modules/term2/node_modules/pty.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o

npm http GET https://registry.npmjs.org/atom-term.js/0.0.55
npm http GET https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/debounce/0.0.3
npm http GET https://registry.npmjs.org/keypather
npm http GET https://github.com/chjj/pty.js/archive/master.tar.gz
npm http 304 https://registry.npmjs.org/fs-plus
npm http 304 https://registry.npmjs.org/keypather
npm http 304 https://registry.npmjs.org/atom-term.js/0.0.55
npm http 304 https://registry.npmjs.org/debounce/0.0.3
npm http 200 https://github.com/chjj/pty.js/archive/master.tar.gz
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/nan
In file included from ../src/unix/pty.cc:16:
../node_modules/nan/nan.h:337:60: error: too many arguments to function call, expected at most 3, have 4
    return v8::Signature::New(nan_isolate, receiver, argc, argv);
           ~~~~~~~~~~~~~~~~~~                              ^~~~
/Users/swaggere/.atom/.node-gyp/.node-gyp/0.11.10/deps/v8/include/v8.h:3550:3: note: 'New' declared here
  static Local<Signature> New(Handle<FunctionTemplate> receiver =
  ^
In file included from ../src/unix/pty.cc:16:
../node_modules/nan/nan.h:365:27: error: cannot initialize a parameter of type 'int' with an lvalue of type 'v8::Isolate *'
    return v8::Array::New(nan_isolate);
                          ^~~~~~~~~~~
/Users/swaggere/.atom/.node-gyp/.node-gyp/0.11.10/deps/v8/include/v8.h:2307:31: note: passing argument to parameter 'length' here
  static Local<Array> New(int length = 0);
                              ^
In file included from ../src/unix/pty.cc:16:
../node_modules/nan/nan.h:370:40: error: too many arguments to function call, expected at most single argument 'length', have 2 arguments
    return v8::Array::New(nan_isolate, length);
           ~~~~~~~~~~~~~~              ^~~~~~
/Users/swaggere/.atom/.node-gyp/.node-gyp/0.11.10/deps/v8/include/v8.h:2307:3: note: 'New' declared here
  static Local<Array> New(int length = 0);
  ^
In file included from ../src/unix/pty.cc:16:
../node_modules/nan/nan.h:375:39: error: too many arguments to function call, expected single argument 'time', have 2 arguments
    return v8::Date::New(nan_isolate, time).As<v8::Date>();
           ~~~~~~~~~~~~~              ^~~~
/Users/swaggere/.atom/.node-gyp/.node-gyp/0.11.10/deps/v8/include/v8.h:2831:3: note: 'New' declared here
  static Local<Value> New(double time);
  ^
In file included from ../src/unix/pty.cc:16:
../node_modules/nan/nan.h:375:56: error: expected '(' for function-style cast or type construction
    return v8::Date::New(nan_isolate, time).As<v8::Date>();
                                               ~~~~~~~~^
../node_modules/nan/nan.h:375:58: error: expected expression
    return v8::Date::New(nan_isolate, time).As<v8::Date>();
                                                         ^
../node_modules/nan/nan.h:380:39: error: too many arguments to function call, expected single argument 'time', have 2 arguments
    return v8::Date::New(nan_isolate, time).As<v8::Date>();
           ~~~~~~~~~~~~~              ^~~~
/Users/swaggere/.atom/.node-gyp/.node-gyp/0.11.10/deps/v8/include/v8.h:2831:3: note: 'New' declared here
  static Local<Value> New(double time);
  ^
In file included from ../src/unix/pty.cc:16:
../node_modules/nan/nan.h:380:56: error: expected '(' for function-style cast or type construction
    return v8::Date::New(nan_isolate, time).As<v8::Date>();
                                               ~~~~~~~~^
../node_modules/nan/nan.h:380:58: error: expected expression
    return v8::Date::New(nan_isolate, time).As<v8::Date>();
                                                         ^
../node_modules/nan/nan.h:383:15: error: no type named 'UnboundScript' in namespace 'v8'
  typedef v8::UnboundScript NanUnboundScript;
          ~~~~^
../node_modules/nan/nan.h:391:9: error: no member named 'ScriptCompiler' in namespace 'v8'
    v8::ScriptCompiler::Source source(s, origin);
    ~~~~^
../node_modules/nan/nan.h:392:16: error: no member named 'ScriptCompiler' in namespace 'v8'
    return v8::ScriptCompiler::CompileUnbound(nan_isolate, &source);
           ~~~~^
../node_modules/nan/nan.h:392:61: error: use of undeclared identifier 'source'; did you mean 'v8::Extension::source'?
    return v8::ScriptCompiler::CompileUnbound(nan_isolate, &source);
                                                            ^~~~~~
                                                            v8::Extension::source
/Users/swaggere/.atom/.node-gyp/.node-gyp/0.11.10/deps/v8/include/v8.h:3677:46: note: 'v8::Extension::source' declared here
  const String::ExternalAsciiStringResource* source() const {
                                             ^
In file included from ../src/unix/pty.cc:16:
../node_modules/nan/nan.h:392:60: error: must explicitly qualify name of member function when taking its address
    return v8::ScriptCompiler::CompileUnbound(nan_isolate, &source);
                                                           ^~~~~~~
                                                            Extension::
../node_modules/nan/nan.h:399:9: error: no member named 'ScriptCompiler' in namespace 'v8'
    v8::ScriptCompiler::Source source(s);
    ~~~~^
../node_modules/nan/nan.h:400:16: error: no member named 'ScriptCompiler' in namespace 'v8'
    return v8::ScriptCompiler::CompileUnbound(nan_isolate, &source);
           ~~~~^
../node_modules/nan/nan.h:400:61: error: use of undeclared identifier 'source'; did you mean 'v8::Extension::source'?
    return v8::ScriptCompiler::CompileUnbound(nan_isolate, &source);
                                                            ^~~~~~
                                                            v8::Extension::source
/Users/swaggere/.atom/.node-gyp/.node-gyp/0.11.10/deps/v8/include/v8.h:3677:46: note: 'v8::Extension::source' declared here
  const String::ExternalAsciiStringResource* source() const {
                                             ^
In file included from ../src/unix/pty.cc:16:
../node_modules/nan/nan.h:400:60: error: must explicitly qualify name of member function when taking its address
    return v8::ScriptCompiler::CompileUnbound(nan_isolate, &source);
                                                           ^~~~~~~
                                                            Extension::
../node_modules/nan/nan.h:405:12: error: no matching function for call to 'NewExternal'
    return v8::String::NewExternal(nan_isolate, resource);
           ^~~~~~~~~~~~~~~~~~~~~~~
/Users/swaggere/.atom/.node-gyp/.node-gyp/0.11.10/deps/v8/include/v8.h:1765:24: note: candidate function not viable: requires single argument 'resource', but 2 arguments were provided
  static Local<String> NewExternal(ExternalStringResource* resource);
                       ^
/Users/swaggere/.atom/.node-gyp/.node-gyp/0.11.10/deps/v8/include/v8.h:1786:24: note: candidate function not viable: requires single argument 'resource', but 2 arguments were provided
  static Local<String> NewExternal(ExternalAsciiStringResource* resource);
                       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2

gyp ERR! stack     at ChildProcess.onExit (/Users/swaggere/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/Users/swaggere/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/mb/281v60z50ml4tw4qk9x25hr40000gn/T/apm-install-dir-114101-42744-13l3a82/node_modules/term2/node_modules/pty.js
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm http 304 https://registry.npmjs.org/underscore
npm ERR! pty.js@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.4 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.0.0
npm ERR! command "/Users/swaggere/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node" "/Users/swaggere/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/swaggere/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/Users/swaggere/.atom/.apmrc" "install" "/Users/swaggere/.atom/.node-gyp/.atom/.apm/term2/0.9.4/package.tgz" "--target=0.11.10" "--arch=x64"
npm ERR! cwd /private/var/folders/mb/281v60z50ml4tw4qk9x25hr40000gn/T/apm-install-dir-114101-42744-13l3a82
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /private/var/folders/mb/281v60z50ml4tw4qk9x25hr40000gn/T/apm-install-dir-114101-42744-13l3a82/npm-debug.log
npm ERR! not ok code 0

```

APM version returns

```
apm  0.69.0
npm  1.4.4
node 0.10.26
```

**Comment by MoOx** [comment]
Related to pty.js, so please open an issue overthere if still relevant. You might want to follow #44 or #132
