### ISSUE TITLE
Fail to install for Atom 0.182.0

### ISSUE THREAD

**Issue by yimingli** [webBoxio/atom-term2#91]
Atom 0.182.0 installed by brew-cask
Mac Yosemite 10.10.2
```
➜  ~  apm -v
apm  0.140.0
npm  2.5.1
node 0.10.35
python 2.7.9
git 2.3.0
```

```
➜  ~  apm install term2
Installing term2 to /Users/paul/.atom/packages ✗

> pty.js@0.2.5 install /private/var/folders/3_/n1zj8wfx1yncxcjfty5_gfjm0000gn/T/apm-install-dir-115124-69813-zn389n/node_modules/term2/node_modules/pty.js
> node-gyp rebuild


gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.4.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)
gyp ERR! stack     at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:766:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:979:11)
gyp ERR! stack     at Socket.emit (events.js:95:17)
gyp ERR! stack     at Pipe.close (net.js:466:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/3_/n1zj8wfx1yncxcjfty5_gfjm0000gn/T/apm-install-dir-115124-69813-zn389n/node_modules/term2/node_modules/pty.js
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.1.0
npm ERR! argv "/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/bin/node" "/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/paul/.atom/.apm/.apmrc" "--userconfig" "/Users/paul/.atom/.apmrc" "install" "/private/var/folders/3_/n1zj8wfx1yncxcjfty5_gfjm0000gn/T/d-115124-69813-1yvwvbp/package.tgz" "--target=0.21.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.2.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/3_/n1zj8wfx1yncxcjfty5_gfjm0000gn/T/apm-install-dir-115124-69813-zn389n/npm-debug.log

➜  ~  apm stars --install
Installing autocomplete-plus to /Users/paul/.atom/packages ✓
Installing fancy-new-file to /Users/paul/.atom/packages ✓
Installing highlight-selected to /Users/paul/.atom/packages ✓
Installing indentation-indicator to /Users/paul/.atom/packages ✓
Installing language-r to /Users/paul/.atom/packages ✓
Installing minimap to /Users/paul/.atom/packages ✓
Installing project-manager to /Users/paul/.atom/packages ✓
Installing set-syntax to /Users/paul/.atom/packages ✓
Installing tabs-to-spaces to /Users/paul/.atom/packages ✓
Installing vim-mode to /Users/paul/.atom/packages ✓
➜  ~  apm install term2
Installing term2 to /Users/paul/.atom/packages ✗

> pty.js@0.2.5 install /private/var/folders/3_/n1zj8wfx1yncxcjfty5_gfjm0000gn/T/apm-install-dir-115124-70215-1ch0cpe/node_modules/term2/node_modules/pty.js
> node-gyp rebuild


gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.4.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)
gyp ERR! stack     at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:766:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:979:11)
gyp ERR! stack     at Socket.emit (events.js:95:17)
gyp ERR! stack     at Pipe.close (net.js:466:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/3_/n1zj8wfx1yncxcjfty5_gfjm0000gn/T/apm-install-dir-115124-70215-1ch0cpe/node_modules/term2/node_modules/pty.js
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.1.0
npm ERR! argv "/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/bin/node" "/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/paul/.atom/.apm/.apmrc" "--userconfig" "/Users/paul/.atom/.apmrc" "install" "/private/var/folders/3_/n1zj8wfx1yncxcjfty5_gfjm0000gn/T/d-115124-70215-1ywu69j/package.tgz" "--target=0.21.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.2.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/3_/n1zj8wfx1yncxcjfty5_gfjm0000gn/T/apm-install-dir-115124-70215-1ch0cpe/npm-debug.log
```

**Comment by jameswalmsley** [comment]
I have exactly the same issue.
Sorry I can't be of assistance as I'm completely new to Atom but just wanted to add a +1 to this issue.

**Comment by liquid1982** [comment]
Same problem here :'(

**Comment by D-side** [comment]
@liquid1982 nope, yours is #90, which contains a detailed discussion on what's wrong. Sadly, it's not system-specific, this package won't work at all on all the recent Atom verisons shipped with `io.js`.

This issue, however, is about `apm` ( calling `node-gyp` specifically) using a wrong version of Python for some reason. And this is system-specific, it can be fixed. After fixing this one though, chances are that you'll hit #90 :dizzy_face:

**Comment by liquid1982** [comment]
@D-side thanks for the update! I am not a Node / Python guy so sadly I am not able to help here. I look forward for using my favourite atom package again soon!

**Comment by MoOx** [comment]
Related to pty. Please comment on #44 or #132 if relevant.
